language: objective-c

osx_image: xcode7.3
   
script: 
   xctool -project ConvenientFileManager.xcodeproj -scheme ConvenientFileManager build -scheme ConvenientFileManagerTests test -sdk iphonesimulator
